all: EuclideanVectorTester

EuclideanVectorTester: EuclideanVectorTester.o EuclideanVector.o
	g++ -g EuclideanVectorTester.o EuclideanVector.o -o EuclideanVectorTester

EuclideanVectorTester.o: EuclideanVectorTester.cpp EuclideanVector.h
	g++ -std=c++14 -Wall -Werror -O2 -g -c EuclideanVectorTester.cpp
EuclideanVector.o: EuclideanVector.cpp EuclideanVector.h
	g++ -std=c++14 -Wall -Werror -O2 -g -c EuclideanVector.cpp

clean:
	rm *o EuclideanVectorTester
